### ISSUE TITLE
Image opening & closing flash

### ISSUE THREAD

**Issue by czirkoszoltan** [terrymun/Fluidbox#88]
In the FluidBox CSS, the transition delay of .fluidbox-closed .fluidbox-wrap img should be somewhat smaller than the transition interval of .fluidbox-ghost. For example, if

``` css
.fluidbox-ghost {
transition: all .25s ease-in-out;
}
```

then

``` css
.fluidbox-closed .fluidbox-wrap img {
transition-delay: .15s;
}
```

This is because when closing the image (going back to the page), the image is zoomed out, and its opacity is decreased to zero; however, there is a short time interval when the opacity is almost zero, but the thumbnail has not yet appeared (because of its transition delay). If the original picture (not the zoomed one) is appearing a bit before the zoom-out animation, the flashing of the background color is avoided.
The same should happen when clicking a thumbnail. The opacity of the original image (the thumbnail in a gallery) should not be immediately decreased to zero, but after a short time interval, to allow the animated-zoomed image to obtain some opacity.
